// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_dynamodb_all_tables_region": "ap-northeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "todolist-dev",
            "region": "ap-northeast-2"
        },
        {
            "tableName": "members-dev",
            "region": "ap-northeast-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "ApiMembers",
            "endpoint": "https://fj8o0wjb0j.execute-api.ap-northeast-2.amazonaws.com/dev",
            "region": "ap-northeast-2"
        },
        {
            "name": "ApiToDoList",
            "endpoint": "https://k74yd50nkd.execute-api.ap-northeast-2.amazonaws.com/dev",
            "region": "ap-northeast-2"
        }
    ]
};


export default awsmobile;
